name             'database_upgrader'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures database-upgrader'
long_description 'Installs/Configures database-upgrader'

version          '0.1.0'
depends 'windows'
depends 'dsc'
depends 'resource'
